Fix pickling of Measurement instances in Python < 3.11
Python 3.11 added a default __getstate__() function to the object class
which allowed pickling to operate.

Without this fix, a highly confusing error would occur:

  TypeError: 'NoneType' object is not callable

Which happened because pickle would get a None value instead of an
attribute error.