hl: jsonify document before raising
Trying to add a dataset from the wrong
product gave me a crash in the error
reporting when running json.dumps()
on a datetime. Run jsonify_document()
before calling json.dumps() so we
don't crash while trying to report
errors.

Also remove the leading space after
the newline so the indentation for
all lines of JSON output is consistent.

Traceback (most recent call last):
  File "/app/bin/datacube", line 10, in <module>
    sys.exit(cli())
             ~~~^^
  File "/app/lib/python3.14/site-packages/click/core.py", line 1631, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.14/site-packages/click/core.py", line 1552, in main
    rv = self.invoke(ctx)
  File "/app/lib/python3.14/site-packages/click/core.py", line 2032, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/app/lib/python3.14/site-packages/click/core.py", line 2032, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/app/lib/python3.14/site-packages/click/core.py", line 1415, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.14/site-packages/click/core.py", line 910, in invoke
    return callback(*args, **kwargs)
  File "/app/lib/python3.14/site-packages/datacube/ui/click.py", line 282, in new_func
    return f(cfg_env, *args, **kwargs)
  File "/app/lib/python3.14/site-packages/datacube/ui/click.py", line 320, in with_index
    return f(index, *args, **kwargs)
  File "/app/lib/python3.14/site-packages/datacube/scripts/dataset.py", line 307, in index_cmd
    index_datasets(
    ~~~~~~~~~~~~~~^
        dataset_stream(remap_uri_from_doc(doc_stream), ds_resolve),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        archive_less_mature=500 if archive_less_mature else None,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/app/lib/python3.14/site-packages/datacube/scripts/dataset.py", line 326, in index_datasets
    index.datasets.bulk_add(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        _mk_dataset_tuples(dss), archive_less_mature=archive_less_mature
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/app/lib/python3.14/site-packages/datacube/index/abstract/_datasets.py", line 682, in bulk_add
    for ds_tup in datasets:
                  ^^^^^^^^
  File "/app/lib/python3.14/site-packages/datacube/scripts/dataset.py", line 162, in _mk_dataset_tuples
    for ds in dss:
              ^^^
  File "/app/lib/python3.14/site-packages/datacube/scripts/dataset.py", line 112, in dataset_stream
    dataset, err = ds_resolve(ds, uri)
                   ~~~~~~~~~~^^^^^^^^^
  File "/app/lib/python3.14/site-packages/datacube/index/hl.py", line 550, in __call__
    dataset, err = self._ds_resolve(doc, uri, source_tree)
                   ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.14/site-packages/datacube/index/hl.py", line 386, in resolve
    return resolver(doc, uri, source_tree=source_tree, **extra_kwargs)
  File "/app/lib/python3.14/site-packages/datacube/index/hl.py", line 235, in resolve_with_lineage
    product = matcher(doc.doc)
  File "/app/lib/python3.14/site-packages/datacube/index/hl.py", line 108, in matcher
    f"\nDataset definition:\n {json.dumps(doc, indent=4)}\n"
                               ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/json/__init__.py", line 242, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "/usr/lib/python3.14/json/encoder.py", line 202, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.14/json/encoder.py", line 263, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.14/json/encoder.py", line 182, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type datetime is not JSON serializable
when serializing dict item 'dtr:start_datetime'
when serializing dict item 'properties'